version: '3'

services:

  alice:
    build:
      context: Alice
      args: 
        - IMAGE_VERSION=ubuntu:latest
    hostname: Alice
    image: own:Alice
    volumes: 
        - ./Files:/root 
    environment:
        - FLASK_ENV=development
    privileged: true
    command: tail -F /dev/null

  bob:
    build:
      context: Bob 
      args: 
        - IMAGE_VERSION=ubuntu:latest
    hostname: Bob
    image: own:Bob
    privileged: true
    command: tail -F /dev/null


networks:

  default:
    external:
      name: rednet
