version: '3'

services:

  alice:
    hostname: Alice
    image: own:Alice
    volumes: 
        - ./Files:/root 
    environment:
        - FLASK_ENV=development
    privileged: true
    command: tail -F /dev/null

  bob:
    hostname: Bob
    image: own:Bob
    privileged: true
    command: tail -F /dev/null


networks:

    default:
        external:
            name: rednet
