#!/usr/bin/env python

import subprocess
import sys
import os

#WRONG INPUT FORMAT
if len(sys.argv) < 3:
    print("scpg [file] [user]")
    exit()

subprocess.call('scp {}:/root/{} /home/gnome/'.format(sys.argv[2], sys.argv[1]), shell=True)
