#!/usr/bin/env python


import subprocess
import sys
import os

#WRONG INPUT FORMAT
if len(sys.argv) < 3:
    print("scpp [file] [user]")
    exit()

subprocess.call('scp {} {}:/root/'.format(sys.argv[1], sys.argv[2]), shell=True)
